'use client';

import { Check, ArrowUpRight } from 'lucide-react';
const plans = [
  { name: 'Starter Launch', tagline: 'Perfect for small businesses starting their digital journey', price: '₹7,999', originalPrice: '₹12,999', period: 'one-time payment', features: ['3–5 Page Business Website', 'Mobile Responsive Design', 'Basic SEO Setup', 'Google Business Profile Setup', 'Lead Capture Contact Form', 'Free Domain (1 Year)', 'Free Hosting (1 Year)', 'Free SSL Security', '1 Year Free Support'], cta: 'Start Growing', highlight: false, savings: 'Save 38%' },
  { name: 'Growth Engine', tagline: 'Complete digital presence for growing businesses', price: '₹14,999', originalPrice: '₹22,999', period: 'one-time payment', features: ['Everything in Starter Launch', '10–15 Page Custom Website', 'Advanced SEO & Google Maps Ranking', 'WhatsApp Chatbot Integration', 'Custom Dashboard (Basic)', 'Free Domain (1 Year)', 'Free Hosting (1 Year)', 'Priority Support (1 Year)'], cta: 'Get Started', highlight: true, savings: 'Save 35%' },
  { name: 'Market Domination', tagline: 'Full-scale digital transformation for market leaders', price: '₹XX,999+', period: 'custom pricing', features: ['Everything in Growth Engine', 'Full Custom Website (20+ Pages)', 'Web or Mobile App Development', 'AI Automation Funnels', 'Advanced Analytics Dashboard', 'Performance Marketing Setup', 'Brand Identity System', 'Free Domain (1 Year)', 'Free Hosting (1 Year)', 'Lifetime Technical Guidance'], cta: 'Book Consultation', highlight: false, savings: null, customPrice: true },
];
const trustItems = ['One-time Payment', 'No Hidden Charges', 'Full Ownership'];
export default function PricingSection() { return <section id="pricing" aria-label="Pricing plans" className="bg-[#fbfafb] py-20 sm:py-28"><div className="section-shell"><div className="mx-auto max-w-2xl text-center"><p className="eyebrow">Trusted by 100+ Businesses</p><h2 className="mt-4 font-display text-4xl font-bold tracking-[-.04em] text-[#211b22] sm:text-5xl">Plans made for <span className="text-[var(--plum)]">your growth</span></h2><p className="mt-5 text-sm leading-7 text-[var(--muted)]">Choose the perfect plan to launch, scale, and dominate your business online with complete support, hosting, and growth-focused solutions.</p></div><div className="mt-12 grid items-stretch gap-5 lg:grid-cols-3">{plans.map(plan => <div key={plan.name} className={`relative flex flex-col border p-6 sm:p-8 ${plan.highlight ? 'border-[var(--plum)] bg-[var(--plum-dark)] text-white shadow-[0_18px_40px_rgba(69,0,72,.2)] lg:-translate-y-3' : 'border-[#e5dce5] bg-white'}`}>{plan.savings && <span className={`absolute right-5 top-5 text-[10px] font-bold uppercase tracking-[.12em] ${plan.highlight ? 'text-[#e5aee3]' : 'text-[var(--plum)]'}`}>{plan.savings}</span>}<h3 className={`text-lg font-bold ${plan.highlight ? 'text-white' : 'text-[#241d25]'}`}>{plan.name}</h3><p className={`mt-2 text-xs leading-5 ${plan.highlight ? 'text-white/65' : 'text-[var(--muted)]'}`}>{plan.tagline}</p><div className="mt-7 flex items-baseline gap-2"><span className="font-display text-4xl font-bold">{plan.price}</span>{plan.originalPrice && <span className={`text-xs line-through ${plan.highlight ? 'text-white/45' : 'text-[#aba2ad]'}`}>{plan.originalPrice}</span>}</div><p className={`mt-1 text-[10px] uppercase tracking-[.12em] ${plan.highlight ? 'text-white/45' : 'text-[#a39aa5]'}`}>{plan.period}</p><ul className="mt-8 flex-1 space-y-3 border-t border-current/10 pt-7">{plan.features.map(feature => <li key={feature} className="flex gap-3 text-xs leading-5"><Check className={`mt-0.5 h-4 w-4 shrink-0 ${plan.highlight ? 'text-[#e6a9e3]' : 'text-[var(--plum)]'}`} /><span className={plan.highlight ? 'text-white/75' : 'text-[#665d68]'}>{feature}</span></li>)}</ul><a href="#contact" className={`mt-8 inline-flex items-center justify-center gap-2 px-5 py-3 text-[10px] font-bold uppercase tracking-[.16em] ${plan.highlight ? 'bg-white text-[var(--plum)] hover:bg-[#f5e7f5]' : 'bg-[var(--plum)] text-white hover:bg-[var(--plum-dark)]'} transition-colors`}>{plan.cta}<ArrowUpRight className="h-3.5 w-3.5" /></a><div className={`mt-5 flex flex-wrap justify-center gap-3 border-t border-current/10 pt-4 text-[9px] uppercase tracking-[.1em] ${plan.highlight ? 'text-white/45' : 'text-[#9f96a1]'}`}>{trustItems.map(item => <span key={item}>{item}</span>)}</div></div>)}</div><p className="mt-12 text-center text-sm text-[var(--muted)]">Need a custom solution? <a href="#contact" className="editorial-link font-semibold">Let's talk about your specific requirements.</a></p></div></section>; }
