'use client';

import Image from 'next/image';
import { ArrowUpRight, CircleCheck as CheckCircle, ChevronRight } from 'lucide-react';
const processTeam = '/process/process-team.jpeg';
const steps = [
  { num: '01', title: 'Business Meeting', desc: 'We connect over a call or WhatsApp to understand your business requirements, products, and target audience.' }, { num: '02', title: 'Custom Strategy', desc: 'We create a simple, tailored digital blueprint, website design mockup, and fixed transparent budget for your project.' }, { num: '03', title: 'Fast Development', desc: 'Our technical team builds your lightning-fast website and sets up your entire Google Maps SEO and business profile.' }, { num: '04', title: 'Launch & Support', desc: 'We launch your brand live on Google and provide you with seamless lifetime technical support.' },
];
export default function ProcessSection() { return <section id="process" aria-label="Our working process" className="bg-[#fbfafb] py-20 sm:py-28"><div className="section-shell"><div className="grid gap-12 lg:grid-cols-2 lg:gap-20"><div><p className="eyebrow">How we work</p><h2 className="mt-4 font-display text-4xl font-bold leading-[1.05] tracking-[-.04em] text-[#211b22] sm:text-5xl">Trusted service, <span className="text-[var(--plum)]">for your various needs</span></h2><p className="mt-6 max-w-md text-sm leading-7 text-[var(--muted)]">A streamlined process designed to deliver results efficiently and transparently from start to finish.</p><div className="mt-7 flex flex-wrap gap-4">{['Transparent Process', 'Fast Delivery', 'Lifetime Support'].map(text => <span key={text} className="inline-flex items-center gap-2 text-xs font-semibold text-[#635a65]"><CheckCircle className="h-4 w-4 text-[var(--plum)]" />{text}</span>)}</div><a href="#contact" className="mt-8 inline-flex items-center gap-2 bg-[var(--plum)] px-5 py-3 text-[10px] font-bold uppercase tracking-[.18em] text-white transition-colors hover:bg-[var(--plum-dark)]">Get in touch <ArrowUpRight className="h-3.5 w-3.5" /></a></div><div className="border-t border-[#e7dfe7]">{steps.map(step => <div key={step.num} className="group grid grid-cols-[42px_1fr_20px] gap-4 border-b border-[#e7dfe7] py-6"><span className="font-display text-xl font-bold text-[var(--plum)]">{step.num}</span><div><h3 className="text-sm font-bold text-[#251e26] group-hover:text-[var(--plum)]">{step.title}</h3><p className="mt-2 text-xs leading-6 text-[var(--muted)]">{step.desc}</p></div><ChevronRight className="mt-1 h-4 w-4 text-[#c4aec5] transition-transform group-hover:translate-x-1 group-hover:text-[var(--plum)]" /></div>)}</div></div><div className="relative mt-14 h-72 overflow-hidden sm:h-96"><Image src={processTeam} alt="NexaWave Digital team building custom websites and SEO systems for clients" fill className="object-cover grayscale-[15%] transition-transform duration-700 hover:scale-105" sizes="(max-width: 768px) 100vw, 1200px" loading="lazy" quality={85} /><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/70 to-transparent p-6"><p className="text-sm font-medium text-white">Our team at work — building digital excellence</p><p className="mt-1 text-xs text-white/70">Rajsamand, Rajasthan — 2024</p></div></div></div></section>; }
