'use client';

import Link from 'next/link';
import { Monitor, Search, Smartphone, Bot, BarChart3, PenTool, ArrowUpRight } from 'lucide-react';

const services = [
  { icon: Monitor, title: 'Website Development', desc: 'Business Websites, Landing Pages & Custom Dashboards. Ultra-fast, beautiful on all devices, tailored to automate your business.', href: '/website-development' },
  { icon: Search, title: 'Smart SEO Systems', desc: 'Google Maps SEO, Business Profile optimization, and organic search domination built from the ground up.', href: '/seo-services' },
  { icon: Smartphone, title: 'App Development', desc: 'Scalable mobile and web applications engineered for performance, reliability, and seamless user experience.', href: '/app-development' },
  { icon: Bot, title: 'AI Automation Funnels', desc: 'Intelligent automation workflows that streamline operations, nurture leads, and convert prospects into customers.', href: '/whatsapp-automation' },
  { icon: BarChart3, title: 'Digital Marketing', desc: 'Data-driven campaigns across Google, Meta, and organic channels to accelerate your growth trajectory.', href: '/social-media-marketing' },
  { icon: PenTool, title: 'Brand Identity', desc: 'Premium branding systems — logo, typography, color, and visual language that builds instant authority.', href: '/website-development' },
];

export default function ServicesSection() { return <section id="services" aria-label="Our digital services" className="bg-white py-20 sm:py-28"><div className="section-shell"><div className="grid gap-12 lg:grid-cols-[.75fr_1.25fr] lg:gap-20"><div><p className="eyebrow">Our service expertise</p><h2 className="mt-4 max-w-md font-display text-4xl font-bold leading-[1.05] tracking-[-.04em] text-[#211b22] sm:text-5xl">Delivering IT solutions for digital services</h2><p className="mt-6 max-w-sm text-sm leading-7 text-[var(--muted)]">Complete digital solutions designed to transform your business and accelerate growth across every touchpoint.</p><a href="#contact" className="mt-8 inline-flex items-center gap-2 border border-[#2c252d] px-5 py-3 text-[10px] font-bold uppercase tracking-[.18em] text-[#2c252d] transition-colors hover:border-[var(--plum)] hover:bg-[var(--plum)] hover:text-white">Our services <ArrowUpRight className="h-3.5 w-3.5" /></a></div><div className="grid border-l border-[#ece5ec] sm:grid-cols-2">{services.map(({ icon: Icon, title, desc, href }) => <Link key={title} href={href} className="group border-b border-r border-t border-[#ece5ec] p-6 transition-colors hover:bg-[var(--lavender)] sm:p-8"><Icon className="h-7 w-7 text-[var(--plum)]" strokeWidth={1.2} /><h3 className="mt-5 text-sm font-bold text-[#251e26] group-hover:text-[var(--plum)]">{title}</h3><p className="mt-3 text-xs leading-6 text-[var(--muted)]">{desc}</p><span className="mt-5 inline-flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.16em] text-[var(--plum)]">Learn more <ArrowUpRight className="h-3 w-3 transition-transform group-hover:translate-x-1 group-hover:-translate-y-1" /></span></Link>)}</div></div></div></section>; }
